name: Deploy to AWS Dev Bucket

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add permissions to the GITHUB_TOKEN
permissions:
  contents: read
  pull-requests: write
  issues: write
  statuses: write
  
env:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: flight-search-app-dev
  AWS_CLOUDFRONT_DISTRIBUTION_ID: E3O865CZUMEY98

jobs:
  build-and-deploy:
    name: 'Build and Deploy to Dev'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build Next.js app
        run: npm run build && npm run export
        env:
          NEXT_PUBLIC_API_URL: https://flight-search-app-dev.s3.amazonaws.com/api
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Deploy to S3
        run: |
          aws s3 sync out/ s3://${{ env.AWS_S3_BUCKET }} --delete
      
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
      
      - name: Deployment Status
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const run_id = context.runId;
            const run_number = context.runNumber;
            const status = '${{ job.status }}';
            
            try {
              // Try to create commit comment first
              await github.rest.repos.createCommitComment({
                owner,
                repo,
                commit_sha: context.sha,
                body: status === 'success'
                  ? `✅ Deployment #${run_number} to dev bucket completed successfully!`
                  : `❌ Deployment #${run_number} failed. Check the [workflow run](https://github.com/${owner}/${repo}/actions/runs/${run_id}) for details.`
              });
            } catch (error) {
              console.log(`Unable to create commit comment: ${error.message}`);
              
              // If PR event, comment on PR instead
              if (context.payload.pull_request) {
                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: context.payload.pull_request.number,
                  body: status === 'success'
                    ? `✅ Deployment #${run_number} to dev bucket completed successfully!`
                    : `❌ Deployment #${run_number} failed. Check the [workflow run](https://github.com/${owner}/${repo}/actions/runs/${run_id}) for details.`
                });
              } else {
                console.log('This is not a PR event, and creating commit comment failed. No status message will be posted.');
              }
            } 